version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: todo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Backend Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - MONGO_URI=mongodb://mongodb:27017/todoapp
      - JWT_SECRET=flazer-code-docker
    depends_on:
      - mongodb

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:5005/api
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
